package:
  name: pem2jwks
  epoch: 0
  version: v0.2.0-8-ge5e81c1-dirty
  description: Converts PEMs to JWKS
  url: https://github.com/mt-inside/go-jwks
  copyright:
    - paths:
        - "*"
      license: Apache-2.0
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - wolfi-base
      - build-base
      - go
pipeline:
  - name: Build
    runs: |
      # build, rather than install, to be able to control output dir
      CGO_ENABLED=0 go build -o "${{targets.destdir}}/usr/bin/pem2jwks" -a -ldflags "-w -X 'github.com/mt-inside/go-jwks/internal/build.Version="${{package.version}}"'" ./cmd/pem2jwks
