name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  binary:
    name: Build and upload binaries
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21'

      - name: Install Just
        uses: extractions/setup-just@v1

      - name: build-linux-amd64
        run: GOOS="linux" GOARCH="amd64" just build-ci -o pem2jwks-Linux-x86_64

      - name: build-linux-arm64
        run: GOOS="linux" GOARCH="arm64" just build-ci -o pem2jwks-Linux-arm64

      - name: build-linux-arm
        run: GOOS="linux" GOARCH="arm" just build-ci -o pem2jwks-Linux-arm

      - name: build-macos-amd64
        run: GOOS="darwin" GOARCH="amd64" just build-ci -o pem2jwks-Darwin-x86_64

      - name: build-macos-arm64
        run: GOOS="darwin" GOARCH="arm64" just build-ci -o pem2jwks-Darwin-arm64

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/pem2jwks-Linux-x86_64
            ${{ github.workspace }}/pem2jwks-Linux-arm64
            ${{ github.workspace }}/pem2jwks-Linux-arm
            ${{ github.workspace }}/pem2jwks-Darwin-x86_64
            ${{ github.workspace }}/pem2jwks-Darwin-arm64
          fail_on_unmatched_files: true
          generate_release_notes: true
          # tag_name: test

  # TODO: dockerhub too - needs secret

  container:
    name: Build and publish container image
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build APK
        id: melange
        uses: chainguard-dev/actions/melange-build@main
        with:
          config: melange.yaml
          archs: x86_64,aarch64
          sign-with-temporary-key: true

      - name: Build & Publish OCI
        id: apko
        # GH: chainguard-images/action/apko-publish
        uses: distroless/actions/apko-publish@main
        with:
          config: apko.yaml
          archs: x86_64,aarch64
          # Will be a SHA, unless this commit is tagged. Which is ideal tbh
          tag: ghcr.io/mt-inside/pem2jwks:${{ github.ref_name }}
          # Default value for melange-build.signing-key-path
          keyring-append: ${{ github.workspace }}/melange.rsa.pub

      # Need to install cosign. Also what keymat does it sign with?
      # - name: Sign OCI
      #   shell: bash
      #   run: COSIGN_EXPERIMENTAL=true cosign sign ${{ steps.apko.outputs.digest }}
