name: release

on:
  push:
    tags:
      - 'v*.*.*'
#on: push

jobs:
  binary:
    name: Build and upload binary
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build-amd64
        run: GOARCH="amd64" go install .
      - name: Hack-amd64
        run: mv /home/runner/go/bin/pem2jwks /home/runner/go/bin/pem2jwks-amd64

      - name: Build-arm64
        run: GOARCH="arm64" go install .
      - name: Hack-arm64
        run: mv /home/runner/go/bin/pem2jwks /home/runner/go/bin/pem2jwks-arm64

      - name: Build-arm
        run: GOARCH="arm" go install .
      - name: Hack-arm
        run: mv /home/runner/go/bin/pem2jwks /home/runner/go/bin/pem2jwks-arm

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            "/home/runner/go/bin/pem2jwks-amd64"
            "/home/runner/go/bin/pem2jwks-arm64"
            "/home/runner/go/bin/pem2jwks-arm"
          fail_on_unmatched_files: true
          generate_release_notes: true

  # TODO: dockerhub too - needs secret
  container:
    name: Build and upload container image
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/mt-inside/pem2jwks:${{ github.ref }}
            ghcr.io/mt-inside/pem2jwks:latest
