name: release

# on:
#   push:
#     tags:
#       - 'v*.*.*'
on: push

jobs:
  binary:
    name: Build and upload binary
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: go install .

      - name: Tets
        run: "go env"

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: "$HOME/go/bin/pem2jwks"
          tag_name: test
