name: test

on: push

jobs:
  binary:
    name: Lint and test
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Just
        uses: extractions/setup-just@v1

      - name: Install tools
        run: just tools-install

      - name: test
        run: just lint
